# Make a list L of dead author names of length 3 or 4
L = ['Agatha Christie', ... 
# print the length of L (should be 3 or 4)
print  ... 
# insert 'Plato' at the end of the list
L... 
# Make another list of length at least 3
Q = ['Goethe', ... ] 
# Add all the authors in Q to L
L... 
# Remove the 2nd and 3rd authors from the list L using slicing
...
# Print each author in L on a separate line, without any quotation marks
... 
